-- contactos.turel.es — listado ampliado de fetiches (11 categorías).
-- Sustituye por completo el listado anterior.
-- Ejecutar con:
--   docker exec -i contactos-db psql -U contactos -d contactos < scripts/update-fetiches-v3.sql

BEGIN;

TRUNCATE fetiches RESTART IDENTITY CASCADE;

INSERT INTO fetiches (nombre, categoria) VALUES
-- AMBIENTE LIBERAL
('Intercambio de parejas','Ambiente liberal'),
('Soft swinging','Ambiente liberal'),
('Full swap','Ambiente liberal'),
('Voyeurismo','Ambiente liberal'),
('Exhibicionismo','Ambiente liberal'),
('Tríos MMF','Ambiente liberal'),
('Tríos FFM','Ambiente liberal'),
('Grupos','Ambiente liberal'),
('Fiestas liberales','Ambiente liberal'),
('Clubes de intercambio','Ambiente liberal'),
('Swinging','Ambiente liberal'),
('Naturismo','Ambiente liberal'),
('Nudismo social','Ambiente liberal'),
('Sexo en público','Ambiente liberal'),
('Juego en público','Ambiente liberal'),
('Hotwife','Ambiente liberal'),
('Cuckold','Ambiente liberal'),
('Stag & vixen','Ambiente liberal'),
-- BDSM Y PODER
('BDSM','BDSM y poder'),
('Dominación','BDSM y poder'),
('Sumisión','BDSM y poder'),
('Switch','BDSM y poder'),
('Sadismo','BDSM y poder'),
('Masoquismo','BDSM y poder'),
('Esclavitud','BDSM y poder'),
('Servidumbre doméstica','BDSM y poder'),
('Entrenamiento de obediencia','BDSM y poder'),
('Control mental','BDSM y poder'),
('Humillación','BDSM y poder'),
('Humillación pública','BDSM y poder'),
('Degradación','BDSM y poder'),
('Daddy/chica','BDSM y poder'),
('Mommy/chico','BDSM y poder'),
('Modificación de conducta','BDSM y poder'),
-- BONDAGE
('Bondage','Bondage y restricción'),
('Shibari','Bondage y restricción'),
('Kinbaku','Bondage y restricción'),
('Cuerda','Bondage y restricción'),
('Cuerda de cáñamo','Bondage y restricción'),
('Bondage exterior','Bondage y restricción'),
('Cadenas','Bondage y restricción'),
('Esposas','Bondage y restricción'),
('Collar y correa','Bondage y restricción'),
('Collares posturales','Bondage y restricción'),
('Mordazas','Bondage y restricción'),
('Mumificación','Bondage y restricción'),
('Privación sensorial','Bondage y restricción'),
('Capuchas','Bondage y restricción'),
-- IMPACTO
('Impact play','Impacto y dolor'),
('Azotes con la mano','Impacto y dolor'),
('Azotes con correa','Impacto y dolor'),
('Azotes con paleta','Impacto y dolor'),
('Flagelación','Impacto y dolor'),
('Látigo de cola única','Impacto y dolor'),
('Pinzas de pezones','Impacto y dolor'),
('Pinzas clover','Impacto y dolor'),
('Pellizcos','Impacto y dolor'),
('Mordiscos','Impacto y dolor'),
('Bofetadas','Impacto y dolor'),
('Tortura genital','Impacto y dolor'),
('Estimulación eléctrica','Impacto y dolor'),
('E-stim','Impacto y dolor'),
-- ROLES
('Role play','Juego de roles'),
('Doctor y enfermera','Juego de roles'),
('Profesor y alumno','Juego de roles'),
('Depredador y presa','Juego de roles'),
('Persecución y captura','Juego de roles'),
('Pet play','Juego de roles'),
('Furry','Juego de roles'),
('Espiritualidad BDSM','Juego de roles'),
('Geisha','Juego de roles'),
('Piratas','Juego de roles'),
-- FETICHES
('Látex','Fetiches y objetos'),
('Cuero','Fetiches y objetos'),
('Lencería','Fetiches y objetos'),
('Lencería vintage','Fetiches y objetos'),
('Medias y mallas','Fetiches y objetos'),
('Corsés','Fetiches y objetos'),
('Monos ajustados','Fetiches y objetos'),
('Spandex','Fetiches y objetos'),
('Tacones altos','Fetiches y objetos'),
('Botas','Fetiches y objetos'),
('Pies descalzos','Fetiches y objetos'),
('Adoración de pies','Fetiches y objetos'),
('Adoración de botas','Fetiches y objetos'),
('Calcetines altos','Fetiches y objetos'),
('Encaje','Fetiches y objetos'),
('Terciopelo','Fetiches y objetos'),
('Panties','Fetiches y objetos'),
('Enaguas','Fetiches y objetos'),
('Metal','Fetiches y objetos'),
('Trajes de gato','Fetiches y objetos'),
-- PRÁCTICAS
('Masajes sensuales','Prácticas sexuales'),
('Tantra','Prácticas sexuales'),
('Besos','Prácticas sexuales'),
('Caricias y abrazos','Prácticas sexuales'),
('Sexo anal','Prácticas sexuales'),
('Penetración doble','Prácticas sexuales'),
('Penetración triple','Prácticas sexuales'),
('Sexo oral','Prácticas sexuales'),
('Cunnilingus','Prácticas sexuales'),
('Rimming','Prácticas sexuales'),
('Bukake','Prácticas sexuales'),
('Squirting','Prácticas sexuales'),
('Orgasmo negado','Prácticas sexuales'),
('Edging','Prácticas sexuales'),
('Masturbación','Prácticas sexuales'),
('Juguetes','Prácticas sexuales'),
('Dildos','Prácticas sexuales'),
('Plugs anales','Prácticas sexuales'),
('Bolas chinas','Prácticas sexuales'),
('Fisting','Prácticas sexuales'),
('Objetos grandes','Prácticas sexuales'),
('Especulums','Prácticas sexuales'),
('Sexo en la ducha','Prácticas sexuales'),
('Sexo en el coche','Prácticas sexuales'),
-- EXHIBICIONISMO
('Hacer vídeos caseros','Exhibicionismo y voyeurismo'),
('Fotografía erótica','Exhibicionismo y voyeurismo'),
('Literatura erótica','Exhibicionismo y voyeurismo'),
('Escritura erótica','Exhibicionismo y voyeurismo'),
('Sexo por teléfono','Exhibicionismo y voyeurismo'),
('Dispositivos de control remoto','Exhibicionismo y voyeurismo'),
('Plugs en público','Exhibicionismo y voyeurismo'),
-- ESTÉTICA
('Tatuajes','Estética y cuerpo'),
('Piercings','Estética y cuerpo'),
('Rapado de cabeza','Estética y cuerpo'),
('Afeitado','Estética y cuerpo'),
('Androginia','Estética y cuerpo'),
('Feminización','Estética y cuerpo'),
('Crossdressing','Estética y cuerpo'),
('Transexual','Estética y cuerpo'),
('BBW','Estética y cuerpo'),
('Barba y vello facial','Estética y cuerpo'),
-- ORIENTACIÓN
('Heterosexual','Orientación y estilo'),
('Bisexual','Orientación y estilo'),
('Heteroflexible','Orientación y estilo'),
('Homosexual','Orientación y estilo'),
('Pansexual','Orientación y estilo'),
('En exploración','Orientación y estilo'),
('Poliamoría','Orientación y estilo'),
('Relación abierta','Orientación y estilo'),
('Amistad liberal','Orientación y estilo'),
('Solo online por ahora','Orientación y estilo'),
('Conocer en eventos','Orientación y estilo'),
('Encuentros espontáneos','Orientación y estilo'),
-- GENERAL
('Aftercare','Intereses generales'),
('Confianza y comunicación','Intereses generales'),
('Educación sexual','Intereses generales'),
('Bienestar y mindfulness','Intereses generales'),
('Baile del vientre','Intereses generales'),
('Noches fet','Intereses generales');

COMMIT;
